services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  api-server:
    build:
      context: ./api-server
    container_name: vercel-api-server
    ports:
      - "9000:9000"
    env_file:
      - ./.env
    environment:
      - REDIS_CLIENT=redis://redis:6379 
      - PORT=9000
      - REDIS_NETWORK=vercel-clone-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  default:
    name: vercel-clone-network
