name: Deploy to VM

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy and restart with PM2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/app/vercel-clone"

          APP_NAME="vercel-be"

          cd $DEPLOY_PATH

          git pull origin main

          npm install

          pm2 reload $APP_NAME
