name: Deploy to VM

on:
  push:
    branches:
      - deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy and restart with PM2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/app/vercel-clone"
          APP_NAME="vercel-be"
          
          cd $DEPLOY_PATH || exit 1

          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          
          nvm use || nvm install node --default

          git switch deployment || exit 1
          
          git pull --ff-only origin deployment || exit 1

          npm install --production || exit 1

          if pm2 describe $APP_NAME > /dev/null; then
            pm2 reload $APP_NAME || exit 1
          else
            echo "PM2 app $APP_NAME not found. Skipping reload."
          fi
